#A
# shoulder_pan_joint: 0.0
# shoulder_lift_joint: -1.57
# elbow_joint: 1.56
# wrist_1_joint: -1.57
# wrist_2_joint: -1.57
# wrist_3_joint: 0

# #B
# shoulder_pan_joint: 0.0
# shoulder_lift_joint: -1.77
# elbow_joint: 1.76
# wrist_1_joint: -1.37
# wrist_2_joint: -1.57
# wrist_3_joint: 0

#C 
shoulder_pan_joint: 0.0
shoulder_lift_joint: -1.57
elbow_joint: 1.76
wrist_1_joint: -1.77
wrist_2_joint: -1.27
wrist_3_joint: 0
